var LibraryNetHack = {
	$nethack_deps: [],
	$nethack: {
	web_init_nhwindows: (a, b) => {},
	web_player_selection: () => {},
	web_askname: () => {},
	web_get_nh_event: () => {},
	web_exit_nhwindows: (a) => {},
	web_suspend_nhwindows: (a) => {},
	web_resume_nhwindows: () => {},
	web_create_nhwindow: (a) => {},
	web_clear_nhwindow: (a) => {},
	web_display_nhwindow: (a, b) => {},
	web_destroy_nhwindow: (a) => {},
	web_curs: (a, b, c) => {},
	web_putstr: (a, b, c) => {},
	web_putmixed: (a, b, c) => {},
	web_display_file: (a, b) => {},
	web_start_menu: (a) => {},
	web_add_menu: (a, b, c, d, e, f, g, h) => {},
	web_end_menu: (a, b) => {},
	web_select_menu: (a, b, c) => {},
	web_message_menu: (a, b, c) => {},
	web_update_inventory: () => {},
	web_mark_synch: () => {},
	web_wait_synch: () => {},
	web_cliparound: (a, b) => {},
	web_update_positionbar: (a) => {},
	web_print_glyph: (a, b, c, d, e) => {},
	web_raw_print: (a) => {},
	web_raw_print_bold: (a) => {},
	web_nhgetch: () => {},
	web_nh_poskey: (a, b, c) => {},
	web_nhbell: () => {},
	web_doprev_message: () => {},
	web_yn_function: (a, b, c) => {},
	web_getlin: (a, b) => {},
	web_get_ext_cmd: () => {},
	web_number_pad: (a) => {},
	web_delay_output: () => {},
	web_change_color: (a, b, c) => {},
	web_change_background: (a) => {},
	web_set_font_name: (a, b) => {},
	web_get_color_string: () => {},
	web_start_screen: () => {},
	web_end_screen: () => {},
	web_outrip: (a, b, c) => {},
	web_preference_update: (a) => {},
	web_getmsghistory: (a) => {},
	web_putmsghistory: (a, b) => {},
	web_status_init: () => {},
	web_status_finish: () => {},
	web_status_enablefield: (a, b, c, d) => {},
	web_status_update: (a, b, c, d, e, f) => {},
	web_can_suspend: () => {},
	},
};
autoAddDeps(LibraryNetHack, '$nethack');
mergeInto(LibraryManager.library, LibraryNetHack);